### ISSUE TITLE
Criação da página sobre

### ISSUE THREAD

**Issue by gnulin** [gnulin/github-master#3]
Vocês poderiam criar uma página de sobre, por favor?

**Comment by gnulin** [comment]
A página está em produção

**Comment by gnulin** [comment]
Validado

**Comment by gnulin** [comment]
Obrigado! Estou aguardando.

**Comment by gnulin** [comment]
Estou aguardando.

**Comment by gnulin** [comment]
Valide o recebimento por e-mail, por favor.

**Comment by gnulin** [comment]
OK, Recebido.

At.,

Robson Santos

**Comment by o-robson-santos** [comment]
Agora, estou conseguindo colaborar nesse projeto.

**Comment by o-robson-santos** [comment]
Você pode colocar seu telefone no site, por favor, **@gnulin?**
